version: "3.3"

services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/url-shortener
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
